#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

#define AUDIO_INPUT_REFERENCE       true
/* 固定使用实测可唤醒的 ES8388 diff2 输入，避免运行时在多个输入间扫描。 */
#define AUDIO_CODEC_ES8388_ADC_INPUT 0xf0
#define AUDIO_CODEC_ES8388_ADC_INPUT_CONTROL3 0x82
/* 命令词识别固定走麦克风声道，不再自动切到参考声道。 */
#define AUDIO_INPUT_AUTO_WAKE_CHANNEL 0

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_11
#define AUDIO_I2S_GPIO_WS GPIO_NUM_13
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_14
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_12
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_10

#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_41
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_42
#define AUDIO_CODEC_ES8388_ADDR ES8388_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_PA_PIN GPIO_NUM_38

/* IMU */
#define BSP_I2C_SCL           GPIO_NUM_42
#define BSP_I2C_SDA           GPIO_NUM_41
#define BSP_IMU_INT           GPIO_NUM_21

#define BUILTIN_LED_GPIO        GPIO_NUM_NC
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC
#define TOUCH1 GPIO_NUM_2
#define TOUCH2 GPIO_NUM_3



#define LCD_SCLK_PIN GPIO_NUM_8
#define LCD_MOSI_PIN GPIO_NUM_7
#define LCD_MISO_PIN GPIO_NUM_NC
#define LCD_DC_PIN GPIO_NUM_6
#define LCD_CS_PIN GPIO_NUM_9
#define LCD_RST_PIN GPIO_NUM_5

#define DISPLAY_WIDTH    320
#define DISPLAY_HEIGHT   172
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY  true

#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 34

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_4
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_INVERT_COLOR true

// POWER_CHARGE_DETECT_PIN removed - using ADC voltage detection instead
#define POWER_ADC_UNIT ADC_UNIT_1
#define POWER_ADC_CHANNEL ADC_CHANNEL_0

#endif // _BOARD_CONFIG_H_
